### ISSUE TITLE
urlSession warning in xcode 15 beta

### ISSUE THREAD

**Issue by tmc** [bufbuild/connect-swift#148]
I see this when using swift connect in the latest xcode:
```
The request of a upload task should not contain a body or a body stream, use `upload(for:fromFile:)`, `upload(for:from:)`, or supply the body stream through the `urlSession(_:needNewBodyStreamForTask:)` delegate method.
```
<img width="892" alt="Screenshot 2023-08-04 at 12 40 15 AM" src="https://github.com/bufbuild/connect-swift/assets/3977/2898cb9a-f749-4a6b-a7c1-1165f3336dc8">

<img width="1189" alt="Screenshot 2023-08-04 at 1 40 51 AM" src="https://github.com/bufbuild/connect-swift/assets/3977/a04305b4-52ec-41c1-9f5e-8bf5767526a5">

**Comment by rebello95** [comment]
👋🏽 @tmc can you share some details on what you did to get this warning to show up and which version of Xcode you're using? I'm not able to reproduce when running all the tests with Xcode 15 beta 15A5160n.

**Comment by j-j-m** [comment]
I am seeing this as well.  basically just server streaming, works in current Xcode but not in beta.

**Comment by rebello95** [comment]
@j-j-m can you please share details on how to reproduce this and which beta you're using?

**Comment by j-j-m** [comment]
Version 15.0 beta 8 (15A5229m)

and I although I am not at liberty to share any of the code my basic usage is as follows

I create a client 

```swift
let _client = ProtocolClient(
            httpClient: URLSessionHTTPClient(),
            config: ProtocolClientConfig(
                host: environment.urlString,
                networkProtocol: .connect,
                codec: JSONCodec()
            )
        )
 ```
  
 I run codegen which produces a server streaming endpoint which returns an async stream, lets call it `client.stream`
 
 ```swift
 let client = MYCodeGenClient(client: _client)
 for try await result in client.stream() {
        // handle result
 }
```

I then get this runtime warning. the same exact code works on the current release of Xcode 14

**Comment by rebello95** [comment]
Thank you! I was able to reproduce, and have a fix proposed here: https://github.com/bufbuild/connect-swift/pull/159
